[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "apache2-foreground"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
healthcheckTimeout = 300

[deploy.envs]
PHP_VERSION = "8.2"
NODE_VERSION = "18.19.0"
COMPOSER_ALLOW_SUPERUSER = "1"
