[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"

[deploy.envs]
PHP_VERSION = "8.2"
NODE_VERSION = "18.19.0"
COMPOSER_ALLOW_SUPERUSER = "1"
