[build]
buildCommand = "chmod +x railway-build.sh && ./railway-build.sh"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"

[deploy.envs]
PHP_VERSION = "8.2"
NODE_VERSION = "18.19.0"
