services:
  - type: web
    name: analyse-interventions
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: /usr/local/bin/start-render
    envVars:
      - key: APP_NAME
        value: "Analyseur d'Interventions"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: postgres
          name: analyse-db
          property: host
      - key: DB_PORT
        fromService:
          type: postgres
          name: analyse-db
          property: port
      - key: DB_DATABASE
        fromService:
          type: postgres
          name: analyse-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: postgres
          name: analyse-db
          property: username
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: analyse-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_SECURE_COOKIE
        value: true

  - type: postgres
    name: analyse-db
    ipAllowList: []
    plan: free
