services:
  - type: web
    name: analyse-interventions
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    buildCommand: ./render-build.sh
    startCommand: apache2-foreground
    envVars:
      - key: APP_NAME
        value: "Analyseur d'Interventions"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: analyse-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: analyse-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: analyse-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: analyse-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: analyse-db
          property: password

databases:
  - name: analyse-db
    databaseName: analyse
    ipAllowList: []
