services:
  - type: web
    name: analyse-interventions
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: /usr/local/bin/start-render
    envVars:
      - key: APP_NAME
        value: "Analyseur d'Interventions"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-tiny-cell-a8nfck52-pooler.eastus2.azure.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_wB9xK2dDjSWm
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_SECURE_COOKIE
        value: true
